package BanqueDelegation;


/**
* BanqueDelegation/CompteEpargne.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

public interface CompteEpargne extends CompteEpargneOperations, BanqueDelegation.Compte, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompteEpargne
