package BanqueDelegation;

/**
* BanqueDelegation/CompteEpargneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

public final class CompteEpargneHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueDelegation.CompteEpargne value = null;

  public CompteEpargneHolder ()
  {
  }

  public CompteEpargneHolder (BanqueDelegation.CompteEpargne initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueDelegation.CompteEpargneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueDelegation.CompteEpargneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueDelegation.CompteEpargneHelper.type ();
  }

}
