package BanqueDelegation;


/**
* BanqueDelegation/CompteCourantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

abstract public class CompteCourantHelper
{
  private static String  _id = "IDL:BanqueDelegation/CompteCourant:1.0";

  public static void insert (org.omg.CORBA.Any a, BanqueDelegation.CompteCourant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BanqueDelegation.CompteCourant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BanqueDelegation.CompteCourantHelper.id (), "CompteCourant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BanqueDelegation.CompteCourant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CompteCourantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BanqueDelegation.CompteCourant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BanqueDelegation.CompteCourant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BanqueDelegation.CompteCourant)
      return (BanqueDelegation.CompteCourant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BanqueDelegation._CompteCourantStub stub = new BanqueDelegation._CompteCourantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BanqueDelegation.CompteCourant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BanqueDelegation.CompteCourant)
      return (BanqueDelegation.CompteCourant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BanqueDelegation._CompteCourantStub stub = new BanqueDelegation._CompteCourantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
