package BanqueDelegation;


/**
* BanqueDelegation/ComptePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

public class ComptePOATie extends ComptePOA
{

  // Constructors

  public ComptePOATie ( BanqueDelegation.CompteOperations delegate ) {
      this._impl = delegate;
  }
  public ComptePOATie ( BanqueDelegation.CompteOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public BanqueDelegation.CompteOperations _delegate() {
      return this._impl;
  }
  public void _delegate (BanqueDelegation.CompteOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public float lire_montant ()
  {
    return _impl.lire_montant();
  } // lire_montant

  public void crediter (float somme_credit)
  {
    _impl.crediter(somme_credit);
  } // crediter

  public void debiter (float somme_debit)
  {
    _impl.debiter(somme_debit);
  } // debiter

  private BanqueDelegation.CompteOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ComptePOATie
