package BanqueDelegation;

/**
* BanqueDelegation/CompteCourantRemunereHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

public final class CompteCourantRemunereHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueDelegation.CompteCourantRemunere value = null;

  public CompteCourantRemunereHolder ()
  {
  }

  public CompteCourantRemunereHolder (BanqueDelegation.CompteCourantRemunere initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueDelegation.CompteCourantRemunereHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueDelegation.CompteCourantRemunereHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueDelegation.CompteCourantRemunereHelper.type ();
  }

}
