package BanqueDelegation;


/**
* BanqueDelegation/CompteEpargneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

public interface CompteEpargneOperations  extends BanqueDelegation.CompteOperations
{
  int taux ();
  void taux (int newTaux);
} // interface CompteEpargneOperations
