package BanqueDelegation;


/**
* BanqueDelegation/CompteCourantRemunereOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

public interface CompteCourantRemunereOperations  extends BanqueDelegation.CompteCourantOperations, BanqueDelegation.CompteEpargneOperations
{
} // interface CompteCourantRemunereOperations
