package BanqueDelegation;

/**
* BanqueDelegation/CompteCourantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

public final class CompteCourantHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueDelegation.CompteCourant value = null;

  public CompteCourantHolder ()
  {
  }

  public CompteCourantHolder (BanqueDelegation.CompteCourant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueDelegation.CompteCourantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueDelegation.CompteCourantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueDelegation.CompteCourantHelper.type ();
  }

}
