package BanqueDelegation;

/**
* BanqueDelegation/CompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BanqueDelegation.idl
* mercredi 24 novembre 2021 09 h 47 WEST
*/

public final class CompteHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueDelegation.Compte value = null;

  public CompteHolder ()
  {
  }

  public CompteHolder (BanqueDelegation.Compte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueDelegation.CompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueDelegation.CompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueDelegation.CompteHelper.type ();
  }

}
