package BanqueHeritage;

/**
* BanqueHeritage/CompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mercredi 24 novembre 2021 09 h 12 WEST
*/

public final class CompteHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueHeritage.Compte value = null;

  public CompteHolder ()
  {
  }

  public CompteHolder (BanqueHeritage.Compte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueHeritage.CompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueHeritage.CompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueHeritage.CompteHelper.type ();
  }

}
