package BanqueHeritage;


/**
* BanqueHeritage/CompteCourantRemunereOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mercredi 24 novembre 2021 09 h 12 WEST
*/

public interface CompteCourantRemunereOperations  extends BanqueHeritage.CompteCourantOperations, BanqueHeritage.CompteEpargneOperations
{
} // interface CompteCourantRemunereOperations
