package BanqueHeritage;


/**
* BanqueHeritage/CompteEpargneHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mercredi 24 novembre 2021 09 h 12 WEST
*/

abstract public class CompteEpargneHelper
{
  private static String  _id = "IDL:BanqueHeritage/CompteEpargne:1.0";

  public static void insert (org.omg.CORBA.Any a, BanqueHeritage.CompteEpargne that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BanqueHeritage.CompteEpargne extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BanqueHeritage.CompteEpargneHelper.id (), "CompteEpargne");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BanqueHeritage.CompteEpargne read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CompteEpargneStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BanqueHeritage.CompteEpargne value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BanqueHeritage.CompteEpargne narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BanqueHeritage.CompteEpargne)
      return (BanqueHeritage.CompteEpargne)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BanqueHeritage._CompteEpargneStub stub = new BanqueHeritage._CompteEpargneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BanqueHeritage.CompteEpargne unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BanqueHeritage.CompteEpargne)
      return (BanqueHeritage.CompteEpargne)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BanqueHeritage._CompteEpargneStub stub = new BanqueHeritage._CompteEpargneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
