package BanqueHeritage;

/**
* BanqueHeritage/CompteCourantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mercredi 24 novembre 2021 09 h 12 WEST
*/

public final class CompteCourantHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueHeritage.CompteCourant value = null;

  public CompteCourantHolder ()
  {
  }

  public CompteCourantHolder (BanqueHeritage.CompteCourant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueHeritage.CompteCourantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueHeritage.CompteCourantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueHeritage.CompteCourantHelper.type ();
  }

}
